version: '3.8'
services:

  postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mlops

  minio:
    image: minio/minio:latest
    env_file:
      - .env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"     # S3 API
      - "9001:9001"     # MinIO Console/UI
    volumes:
      - miniodata:/data
    networks:
      - mlops

  mlflow:

    build:
      context: .
      dockerfile: Dockerfile.mlflow

    env_file:
      - .env
    command: >
      mlflow server
        --backend-store-uri ${MLFLOW_BACKEND_STORE_URI}
        --default-artifact-root ${MLFLOW_DEFAULT_ARTIFACT_ROOT}
        --host 0.0.0.0
        --port 5000
    ports:
      - "5001:5000"
    depends_on:
      - postgres
      - minio
    networks:
      - mlops
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s


volumes:
  pgdata:
  miniodata:

networks:
  mlops:
